### ISSUE TITLE
Crashed when an invalid url passed

### ISSUE THREAD

**Issue by hiql** [robtaussig/react-use-websocket#106]
Passing an invalid socket server url causes the react component crashed.
I have no idea How shoud I handle this error?

**Comment by tagdara** [comment]
This solution doesn't actually work with the hook.  I still get "Unhandled Rejection (SyntaxError): Failed to construct 'WebSocket': The URL 'wss://(bad url here)/websocket' is invalid, regardless of where I establish the EventBoundary.  

Since it's a hook, you can't put it in a try/except loop either.
