### ISSUE TITLE
Update query params

### ISSUE THREAD

**Issue by astritspancasd** [robtaussig/react-use-websocket#122]
I have a buildWsURL function that gets token from localstorage and appends it to the url as a query param.

```
const buildWsURL= () => {
   const token = localStorage.getItem('token');
   return `ws://something?auth=${token}`
};

```

Most of the time connection closes because this token expires after 5 mins. Any idea how to update websocket url on reconnection?

```
const { sendMessage, lastMessage, readyState } = useWebSocket(
    buildWsURL(),
    {
      onError: (e) => {},
      onOpen: (e) => {},
      onMessage: (e) => {},
      onClose: (e) => {},
      shouldReconnect: (closeEvent) => {
        return true;
      },
      reconnectAttempts: 10,
      reconnectInterval: 3000,
    }
  );
```

**Comment by robtaussig** [comment]
Hi @astritspancasd 

I'd recommend using tracking the token in local state and passing it through`options.queryParams`. Then you can use the `onReconnectStop` callback to generate a new token:

```tsx
  const Component = () => {
    const [token, setToken] = useState(localStorage.getItem('token'));
    const { sendMessage, lastMessage, readyState } = useWebSocket(
    'ws://something',
    {
      queryParams: { auth: token },
      onError: (e) => {},
      onOpen: (e) => {},
      onMessage: (e) => {},
      onClose: (e) => {},
      shouldReconnect: (closeEvent) => {
        return true;
      },
      reconnectAttempts: 10,
      reconnectInterval: 3000,
      onReconnectStop: async () => {
        const newToken = await getNewToken();
        setToken(newToken);
      }
    }
  );
  }
```

When you call `setToken` in `onReconnectStop`, and provided a new token value, `react-use-websocket` will open a new `WebSocket` when the queryParams change. If you don't want to wait 30 seconds to generate a new auth token and reconnect, you can lower the # of `reconnectAttempts` and `reconnectInterval`, if you assume that any unexpected close event will be caused by an expired token, you may want to lower `reconnectAttempts` to `1`, so that it tries once to reconnect before generating a new token.
