### ISSUE TITLE
Add option to retry reconnection after the web socket connection has been closed

### ISSUE THREAD

**Issue by tklepzig** [robtaussig/react-use-websocket#17]
Currently, the only way of "reconnecting" can be done by rerendering the component and so the hook by changing the URL. 

I'd like to have an option whether the connection should try `n` reconnect attempts after the connection has been closed (e.g. the server shut down unexpectedly). I'm fine with contributing by a PR, but currently, I've no good idea how to add this into your implementation, do you have?

**Comment by robtaussig** [comment]
@tklepzig 

Great question. I need to update the README, but an attempt to solve this problem should be available by adding "retryOnError":true to the options object. Reconnect is called on an interval and with a max attempt count, and only triggered on the websocket's error event, so happy to discuss a better approach! (since it might take a while for server to restart, etc)

The challenge I found was differentiating between a "good" disconnect and a bad one. Perhaps accepting a shouldReconnnect callback as an option that passes the close/error event, and if true is returned, it will attempt to reconnect. Thoughts?

**Comment by tklepzig** [comment]
Yep, I already tried the `retryOnError` option (found it in the code ;)) but as you mentioned already, it handles only the error case and when I shut down the server only the close event is triggered.

Nevertheless, I'd let the `retryOnError` implementation as it is (maybe allow defining the `RETRY_LIMIT` in the options) and add a new one for the close event. 

I definitely like your idea with the `shouldReconnnect` callback. Additionally, I'd suggest adding two more options:

- sth like `reconnectionMaxAttempts` (default `Infinity`): How often should we try to reconnect?
- sth like `reconnectionDelay` (default `5000`): How long to wait between reconnection attempts.

Actually, I'm orienting at the options of socket.io: https://socket.io/docs/client-api/#Manager

What do you think?

**Comment by benesva4** [comment]
I think it would be nice to get reconnect function from the useWebSocket so we can use it on our own.
Something like:

`const [sendMessage, lastMessage, readyState, reconnect] = useWebSocket(url, options);`

**Comment by tklepzig** [comment]
> I think it would be nice to get reconnect function from the useWebSocket so we can use it on our own.
> Something like:
> 
> `const [sendMessage, lastMessage, readyState, reconnect] = useWebSocket(url, options);`

Yes, this is another possible approach. Though, you have to handle the reconnecting attempts and delays (e.g. by using `setInterval`) by your own then. 
I'd prefer to handle this stuff inside the hook.

**Comment by robtaussig** [comment]
I tend to agree with @tklepzig here. It's not that I don't trust users to be able to manage the websocket directly, but I'm really trying to isolate implementation details as much as possible, and only expose what is needed to effectively use a websocket (sending a message, receiving messages and updating a component, and tracking current state of the websocket, at minimum). Especially because part of the library aims to allow multiple components to share a single websocket, exposing a function to effectively close a websocket seems like a lot of power to give to every subscriber. Of course, if that was the only way to solve this, it would be worth it.

I actually hit this same problem at work (treating the close event as something that warrants a reconnect attempt, but only where the close event was intended), so I will look into employing a similar approach to how I solved it there. I will also expose more options to allow the component an opportunity to opine on reconnect behavior: reconnect attempts and delay seem like obvious candidates, and I don't see the harm in a shouldReconnect callback. It would be funny deciding on what to do if multiple subscribers return a different boolean value for the same close event, but you can only lead a horse to water, and all that...

**Comment by robtaussig** [comment]
@tklepzig @benesva4 

Just pushed out the changes pertaining to our conversation and in doing so decided that it made more sense to bump library to 1.0.0 instead of 0.9.9:)

[Updated documentation on API](https://github.com/robtaussig/react-use-websocket#reconnecting)

Thanks for your feedback and patience!

**Comment by tklepzig** [comment]
Great, I like it. Thanks a lot for your fast reaction and implementation!

**Comment by kingctan** [comment]
i tried but not work using shouldReconnect(). how to fix it?

```
  const dynamicPropRef = useRef(true);
  // dynamicPropRef.current = true; /*some prop you want to use in the options callbacks*/

  const options = useMemo(() => ({
    share: true,
    onMessage: message => console.log(`onMessage with access to dynamicProp: ${dynamicPropRef.current}`, message),
    onClose: event => console.log('onClose', event),
    onError: error => console.log('onError', error),
    onOpen: event => console.log('onError', event), //{initData(event)},
    // fromSocketIO: true,
    // queryParams: { 'user_id': 1 },
    shouldReconnect: () => dynamicPropRef.current === true, //If websocket closing is intentional, can set dynamicPropRef to false to avoid unnecessary reconnect attempts
    // retryOnError:true,
    reconnectInterval:1000,
    reconnectAttempts:10
  }), []);
```

**Comment by SnowBeforeSpring** [comment]
I got the same problem, have you resolved this problem?
