### ISSUE TITLE
[4.2.0] can't set binaryType to 'arraybuffer'

### ISSUE THREAD

**Issue by prodrive11** [robtaussig/react-use-websocket#171]
> Property 'binaryType' does not exist on type 'WebSocketLike'

when following example:

```
 useEffect( () => {
        getWebSocket().binaryType = 'arraybuffer'
   ....
```

looks like `getWebSocket()` returns [type](https://github.com/robtaussig/react-use-websocket/blob/4ba9fa111a4cce76c2fdb2f623c14f68093c20b7/src/lib/use-websocket.ts#L41):
```
const getWebSocket: () => WebSocketLike | null
```

Also i need to send byte array after switching to `arraybuffer`, not sure current `send` API supports it.

**Comment by robtaussig** [comment]
The problem is `WebSocketLike` covers a few different structures (either a `WebSocket` or an `EventSource`, based on the options you provide it). I could probably restructure the types so that the return value of `getWebSocket` could be inferred based on the options you provide, but in the meantime, this should work for you:

```tsx
useEffect( () => {
        const webSocketLike = getWebSocket();
        if (webSocketLike && 'binaryType' in webSocketLike) { //TypeScript now knows that it is neither null nor an EventSource
            webSocketLike.binaryType = 'arraybuffer'; //TypeScript is ok with this
        }
   ....
```

As for sending the byte array, `sendMessage` ultimately calls `WebSocket#send` directly, and so it should be capable of sending whatever the native WebSocket can. As for TypeScript, this is what the message must adhere to:

```ts
export type WebSocketMessage = string | ArrayBuffer | SharedArrayBuffer | Blob | ArrayBufferView;
```
