### ISSUE TITLE
Error when using react-hot-loader

### ISSUE THREAD

**Issue by geofflittle** [robtaussig/react-use-websocket#20]
Hey there,

I'm brand new to react and using this lib has been great, thanks for writing it.

One sharp edge that I've run into is that when I'm dev'ing with react-hot-loader and make a change I see the error

```
Error: The options object you pass must be static
```

I *think* this might be because when I make a change, the hot reloader re-renders the page (including recreating the WebSocket?) which causes react-use-websocket to think that the options object has changed?  I'm not a 100% sure.

Any help would be greatly appreciated!

Thanks,
Geoff

**Comment by robtaussig** [comment]
Hi Geoff!

Thanks for using the library, and for the interesting question.

I haven't experimented much with react-hot-loader myself, but here is my theory after taking a look at your repo:

1) The first thing I notice is that you aren't passing an options object to useWebSocket. There's nothing wrong with this as all of the options are optional (and thus the options object itself is an optional param), so the fact that this error is being thrown is quite strange (I'll explain below the reason this error exists at all).

2) Theoretically, the only way that error should display is if the options object used inside of the hook changes in reference during the lifecycle of the component, and since you aren't passing one in, then that tells me it is the default options object I defined as a fallback (which is just an empty object to avoid having code like `if (options) //index into options`). Furthermore,  this object is defined at the module level and not inside the component itself. So...

3) Without knowing how react-hot-loader works (and to be honest, if this is even possible), my guess is that when react-hot-loader hot-loads your changes, a new execution context is created which creates a brand new options object. If it is able to achieve this without actually unmounting your react-application, then this error makes sense (although it means I have a lot to learn about JavaScript, as I would have assumed that wasn't possible). As an experiment, try this in your [file](https://github.com/geofflittle/cam-and-geoff/blob/master/src/client/components/room.tsx):

```ts
const STATIC_OPTIONS = useMemo(() => ({}), []);
const [sendMessage, lastMessage, readyState] = useWebSocket(
        "wss://rbi2y7shx0.execute-api.us-east-1.amazonaws.com/dev",
        STATIC_OPTIONS
);
```

The only way STATIC_OPTIONS changes there is if the component is re-mounted during the hot-loading phase, and if it remounts, then the static options check should reset as well (thus avoiding the error). Let me know if that works!

**Comment by geofflittle** [comment]
Hey Rob!

Thanks for getting back to me, I really appreciate it.  I tried your suggestion but unfortunately I'm still seeing the error.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3976777/70387812-88257d80-195e-11ea-95be-829777cb425c.gif)

Any other trouble-shooting suggestions I should try?

Thanks again,
Geoff

**Comment by robtaussig** [comment]
Hi @geofflittle!

Apologies for the late reply. The error is clearly occurring based on your screencast, but oddly enough I am not able to reproduce it after cloning your repo, running `yarn install`, and then `yarn run client:dev` (and making changes to trigger a hot reload). Perhaps you can try a fresh install of node_modules in case there were any recent updates to a library that fix the issue? And what node version are you running?

Regardless, I pushed out a change to support a new option property: `enforceStaticOptions`. If you set it to false, then the error will not be thrown. I updated the documentation as well, but note that any bugs that result from an options object being recreated in mid-lifecycle of a component will be low priority!
