### ISSUE TITLE
Ionic: Close connection on page change.

### ISSUE THREAD

**Issue by Facj** [robtaussig/react-use-websocket#35]
When using Ionic, pages may not be unmounted when switching between them.  
As a result, the suggested mechanism to unsubscribe to data sources is to use Ionic lifecycle events instead of React methods useEffect and omponentWillUnmount. ([docs](https://ionicframework.com/docs/react/lifecycle#guidance-for-each-lifecycle-method)).
As far as I understand, this is not compatible with the mechanism in this package, where the websocket connection is closed when the component is unmounted. 

Is it possible to adapt this behavior to Ionic? Or is there any way to allow users to open/close connections on ionic lifecycle methods?

**Comment by robtaussig** [comment]
Hi @Facj,

I am not familiar with Ionic, so I was hesitant to attempt any solution that depends on specific knowledge of it. That said, your issue is similar to others that have been brought up in the past that result from the limited access the library provides to the underlying websocket. My original motivation behind this was to protect against bugs caused by multiple components using the same (shared) websocket where one component calls a method/sets a property on the websocket without the knowledge/coordination of other components.

What I've done is modify the behavior of the getWebSocket function -- instead of returning a proxy to the websocket (that prevents invocation of the websocket methods), it returns the underlying websocket, but only if the websocket is not shared. As such, you are free to close the websocket directly depending on the particular Ionic lifecycle event.

10cedea
