### ISSUE TITLE
Allow shared websockets to be closed

### ISSUE THREAD

**Issue by raphael-leger** [robtaussig/react-use-websocket#43]
I would like to be able to close a websocket connection, even if it is shared.

The connection would be closed from one of the components using it.
The other components would handle it well: thanks to the `readyState` flag they will know they can't send messages anymore, and they would not receive messages anymore as well.

> If the websocket is shared, calling this function will lazily instantiate a Proxy instance that wraps the underlying websocket. You can get and set properties on the return value that will directly interact with the websocket, however certain properties/methods are protected (cannot invoke close or send.)

Why are there such limitations? Can we remove them?

**Comment by robtaussig** [comment]
Hi Raphael,

I understand your frustration. For context, when implementing this feature, I viewed components that use a shared websocket as the subscribers of a pub-sub model, and felt that it was giving too much power to each subscriber to allow it to effectively unsubscribe on behalf of other subscribers by closing the websocket. I know this is not a perfect analogy, but that was the original motivation.  That said, by limiting your access to the 'hub' of this pattern, I can see why this might be too restrictive and opinionated.

The other challenge is that the current usage pattern is to open a websocket by defining a url in the first param for useWebsocket, and you close it by setting the url to null. This effectively allows you to control websockets in a 'React'-way by setting and unsetting a state variable/context value that holds the socket url. In cases where a url is provided and the websocket closes, then the natural behavior is to attempt to reconnect. However, if we allow situations in which the url is defined, but the websocket is closed via an exposed method, then presumably we do not want it to reconnect. So now we are in a situation where a url is defined, but the websocket is closed. Without any other changes, reopening it would require arbitrarily setting the url to null and then back to the url -- something that I found clunky. While this is already possible with non-shared websockets, I felt it was not as problematic if a component put itself in that position, but where multiple components are relying on one websocket, I didn't like the situation where each component suddenly disconnects and may or may not attempt to reconnect based on its other preferences/implementation.

I've thought about adding an option where a component declares itself the 'hub' (or perhaps assign this to the first shared component), and give it the exclusive ability to close/re-open a websocket, but I haven't experimented with this yet.

Out of curiosity, do you see any problem with passing your shared websocket url (and a setter) through React's Context API, and instead of having a component close the websocket in your example, have that component set the global value to null? This should achieve the same goal, while (in my opinion) being a bit more React-ish.

**Comment by robtaussig** [comment]
Closing this for now.
