### ISSUE TITLE
filter received messages by the result of useEffect

### ISSUE THREAD

**Issue by YikSanChan** [robtaussig/react-use-websocket#47]
Hi,

I have a use case where:
- The component mounts
- const [whitelistedIds, setWhitelistedIds] = useState([])
- useWebSocket(url, {filter: msg => whitelistedIds.contains(parse(msg))})
- useEffect is triggered after the first render, which pulls whitelistedIds and setWhitelistedIds

However, at the very moment useWebSocket is triggered, whitelistedIds is empty, thus the filter does not work as expected.

An obvious solution is to not pass in the `filter` and handle the filter logic inside the component that uses useWebSocket. It is simple and it works fine.

An obvious workaround is fetching whitelisted ids in the parent component, and pass it down as props. However, in my case, whitelisted ids are derived from route params passed into the component, and conceptually, its parent should not be aware of this.

Another workaround is to have options take a `filter` with return type `Promise`, but that makes the API complex and doesn't seem worth it.

I kinda prefer the 1st solution, what do you think maybe a better solution?

**Comment by robtaussig** [comment]
Hi @YikSanChan,

Would you mind updating your repo with this? This would have definitely been an issue prior to v2, which required static options, but v2 should work with this. So first suggestion is to update to v2 if you haven't done so, and if you have, make sure that you are not using the useMemo implementation (which based on your second bullet point, it looks like you're good so far). Also, is it possible that there is a race condition going on? If you are fetching the whitelistedIds from a server, then maybe the messages that should be filtered are being received before the whitelist request.

In the meantime, your 1st solution is the cleanest, but ideally unnecessary (since it would appear the filter doesn't actually work).

Another potential solution is to defer instantiating the websocket until you retrieve the whitelistedIds. This not only avoids the potential race condition above, but follows the logical order of operations: before the component starts receiving messages, it should know what messages it actually cares about. If you do not want to achieve this via fetching from parent and rendering the child with ids in hand, then you can achieve this using the (new as of v2) third param:

```tsx
const [whitelistedIds, setWhitelistedIds] = useState([])
const { /*...*/} = useWebSocket(url,
    {filter: msg => whitelistedIds.contains(parse(msg))},
    whitelistedIds.length > 0
)
```
While the length is 0, the websocket will not connect. Once it is greater than 0, the websocket connects, and the onmessage handler will bind with the latest whiteListedIds list. This solution is only sound if you only expect the whiteListedIds to update once.

**Comment by YikSanChan** [comment]
> Would you mind updating your repo with this?

Do you mean having a reproducible demo?

Yah, I am on v2, and I like the third-param solution, very nice. Thank you so much for the work!
