### ISSUE TITLE
Cannot JSON.parse received data when using socket.io

### ISSUE THREAD

**Issue by GGAlanSmithee** [robtaussig/react-use-websocket#8]
When using socket.io, I am emitting a message from the server:

`io.emit('test', 'hello, world!')`

but on the client (in the received MessageEvent), it results in:

`data: "42["test","hello, world!"]"`

or, in case of using an actual JSON payload:

`io.emit('test', { message: 'hello, world!' })`

on the client:

`data: "42["test",{"message":"hello, world!"}]"`

(Also, in case of using `send` instead of `emit`, the result is the same.)

which are both none-parseable as a JSON object. Is this expected or is this a a user error? My test setup is very minimal with the following config:

```js
const Test = () => {
    const options = useMemo(
        () => ({
            share: true,
            fromSocketIO: true,
            onMessage: (_event: MessageEvent) => {},
            onClose: (_event: MessageEvent) => {},
            onOpen: (_event: MessageEvent) => {},
            onError: console.error,
        }),
        [],
    )

    const [sendMessage, lastMessage, readyState] = useWebSocket(
        'ws://localhost:3000',
        options,
    )

    console.log(lastMessage)

    return (
        <div />
    )
}
```

Thanks in advance, AS

**Comment by robtaussig** [comment]
Hi Alan,

I should definitely document socket.io support better, because this is an example of where the library is not a drop-and-replace alternative to it. What it does is convert the url to one that socketIO listens for on the backend (assuming basic configuration), and implements a ping system that it expects from the client. You can see the basic functionality [here](https://github.com/robtaussig/react-use-websocket/blob/master/src/lib/socket-io.js).

What it does not do is parse the messages that socket.io generates from the backend. My original goal was to minimize abstraction, while providing a familiar React-like API for interacting with sockets (as opposed to instantiating and storing a socket, adding event listeners, etc). I can definitely be convinced otherwise, but my opinion is that you can always go from SocketIO message -> something parsable in JSON if the message is passed along unparsed, but you can't really go the other way around without reverse engineering how the library decides to parse it. Here is something I did for this exact problem on a project I worked on:

```
// The actions are project-specific for a chat application. The parsed messages will look like
// [<messageType>, <payload>]
export const MESSAGE_TYPES = {
  RECEIVED_ID: 'receive id',
  SEND_MESSAGE: 'send message',
  RECEIVED_MESSAGE: 'chat message',
  UPDATE_USERS: 'update users',
  USER_TYPING: 'user typing',
  USER_CONNECTED: 'user connected',
  USER_DISCONNECTED: 'on leave team text room',
  SOCKET_IO_META: 'SOCKET_IO_META', //SocketIO sends responses to every ping message
  NULL_MESSAGE: 'NULL_MESSAGE',
};

const actionsToMessageTypes = action => ({
  'receive id': MESSAGE_TYPES.RECEIVED_ID,
  'update users': MESSAGE_TYPES.UPDATE_USERS,
  'on leave team text room': MESSAGE_TYPES.USER_DISCONNECTED,
  'chat message': MESSAGE_TYPES.RECEIVED_MESSAGE,
  'user typing': MESSAGE_TYPES.USER_TYPING,
  'send message': MESSAGE_TYPES.SEND_MESSAGE,
  'user connected': MESSAGE_TYPES.USER_CONNECTED,
})[action];

export const fromSocketIO = message => {
  if (message) {
    const regexPayload = /^\d+(\[.*\])$/.exec(message.data); //Strip out the leading integer to make it JSON-parsable
    if (regexPayload) {
      const result = regexPayload[1];
      if (result) {
        return JSON.parse(result);
      } //If no result, then the message is just an integer, which is auto-generated by socketIO backend
    }
  
    return {
      type: MESSAGE_TYPES.SOCKET_IO_META,
    };
  }
  return {
    type: MESSAGE_TYPES.NULL_MESSAGE,
  };
};
```

**Comment by robtaussig** [comment]
I was thinking about this problem today, and came up with what I hope is a satisfactory solution:

It is undesirable for your component to get updated and re-render on every message received from SocketIO, as many of those are simple ping responses and other messages that are communicating information that isn't relevant to your component. To combat this, I've added another optional key-value pair for the options argument: `filter`. If defined as a function, all incoming messages will be passed through as a param, and only trigger an update if it returns `true`.

So using the above parsing logic, you could return true where it is otherwise returning `JSON.parse(result)` in order to filter all irrelevant messages.

I also added documentation on the behavior you described, along with a simplified parser. Thanks for bringing this to my attention, and I hope you are ok with me closing this issue.

**Comment by GGAlanSmithee** [comment]
@robtaussig thanks for the explanation and additional work. What you say makes sense, and I actually ended up doing something in the lines of what you do:

I created an abstraction hook over the on you provide out of the box, where I handle message parsing, updates, memoization etc.

```ts
import { useMemo } from 'react'
import useWebSocket from 'react-use-websocket'

interface ISocketIOEvent {
    type: string
    payload: any
}

const emptyEvent: ISocketIOEvent = {
    type: 'empty',
    payload: null,
}

const getSocketData = (event: MessageEvent) => {
    if (!event || !event.data) {
        return emptyEvent
    }

    const match = event.data.match(/\[.*]/)

    if (!match) {
        return emptyEvent
    }

    const data = JSON.parse(match)

    if (!Array.isArray(data) || !data[1]) {
        return emptyEvent
    }

    return {
        type: data[0],
        payload: data[1],
    }
}

const useSocketIO = (): ISocketIOEvent => {
    const options = useMemo(
        () => ({
            share: true,
            fromSocketIO: true,
            onMessage: (_event: MessageEvent) => {},
            onClose: (_event: MessageEvent) => {},
            onOpen: (_event: MessageEvent) => {},
            onError: console.error,
        }),
        [],
    )

    const [, lastMessage] = useWebSocket(
        'ws://localhost:3000', // todo - use secure wss
        options,
    )

    return useMemo(() => getSocketData(lastMessage), [lastMessage])
}

export { ISocketIOEvent, useSocketIO }
```

(since I'm only interested in the last data for the time being, I don't return `sendMessage` or `readyState`, but that could be added ofcourse.

**Comment by robtaussig** [comment]
I like it. If you are interested, this can potentially be a useful add-on that a developer can import into their component instead of the core hook, so they don't have to think about socketIO parsing.

**Comment by GGAlanSmithee** [comment]
Sen you a PR @robtaussig
