### ISSUE TITLE
Web Socket share = true is creating multiple instances

### ISSUE THREAD

**Issue by sachin-agarwal-by** [robtaussig/react-use-websocket#81]
I am using react-use-websocket and observe that as per documentation if we add shared as true then same web socket connection needs to be share for same request url. But In my case I have created a sample application in which I am using webSocket Connection in app.tsx which is like to maintain websocket at application level and then we are using for websocket per Screen for example from Home screen .. In both the screen Websocket url is same with same connection id but it you observer the console .log we are getting two times web socket connection and its connecting twice and opened twice for each instance..

Attached examample for same in codesandbox.
@robtaussig 

https://codesandbox.io/s/cool-fast-kl6ms

**Comment by sachin-agarwal-by** [comment]
@robtaussig Can someone look into this please.

**Comment by SrinivasSwaroop-Dev** [comment]
Facing the same @robtaussig kindly look into this at the earliest

**Comment by robtaussig** [comment]
Hi @sachin-agarwal-by,

I'm using your sample application, and am only seeing one websocket instance created. Please confirm that I am testing correctly:

1) Open https://codesandbox.io/s/cool-fast-kl6ms
2) Click 'Home' at top

--------

To verify # of websocket instances, you will need to open devtools and look at the network tab. You can make this easier by selecting 'WS' as the filter. It might help to clear the network log and then refresh to make sure you are starting from scratch. After doing this and then following the above steps, I see only one websocket:

[Screenshot](https://i.imgur.com/LzvfE74.png)
-------

The console.logs you see are not indicative of how many websockets are being opened, but I can see where the confusion comes from -- even where a component uses a shared websocket, the readyState property will always begin as 'CONNECTING' (even if the shared websocket has already been opened by another component). The reason for this is a bit arbitrary, but ultimately it is because the library accepts an async function for the url, which allows consumers of the library to dynamically generate resource urls. Once the url has been 'determined' (either as the return value of an async function or because you provided a static url), a websocket is either opened with that url, or if it already exists and is shared, the hook will return the readyState for that websocket. But again, per component, it will always start at CONNECTING.

The other source of confusion might be the onOpen message: I believe what is happening is that you area opening a websocket on the first page-load, and then click on HOME before the open event fires. At this point, since the OPEN event has not yet happened, the onOpen event triggers for both listeners. In my testing, if I waited for the OPEN event to trigger before clicking on HOME, then the event will only fire once from the home page.

**Comment by sachin-agarwal-by** [comment]
Thanks @robtaussig for detail explanations . I got doubt from the same place as you mentioned "The console.logs you see are not indicative of how many websockets are being opened" , So Its clear now and I can see we are only maintaining only one web socket instance.

I would like to bring one more point here that Did you face any scenario where the websocket connection ready state is in CONNECTING and we sent the websocket request and after that ready state changed to OPEN , but we will not get any response for the websocket .

This scenario we are facing in our application but I am not able to repro in the same codebox environment. So just checking with you for any heads up for similar issue u faced ?

**Comment by sachin-agarwal-by** [comment]
@robtaussig  sure , thanks for ur help, I will try to repro the scenario in codesandbox if anyhow I am able to do.
